package:
  name: {{ cookiecutter.module_name|tojson }}
  version: "0.0.1"

source:
  git_url: "https://github.com/MAPC/{{ cookiecutter.repo_name }}.git"

build:
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation .
  number: 0
  string: dev
extra:
  channels:
    - default
    - conda-forge

requirements:
  build:
  run:

source:
  path: .

about:
  home: "https://github.com/MAPC/{{ cookiecutter.repo_name }}"
  license: MIT
  license_file: LICENSE
  summary: {{  cookiecutter.description|tojson }}
  description: See the package README.md for more information.
  dev_url: "https://github.com/MAPC/{{ cookiecutter.repo_name }}"
